-- public."Districts" определение
CREATE TABLE public."Districts" (
	"Id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Name" text NOT NULL,
	CONSTRAINT "PK_Districts" PRIMARY KEY ("Id")
);


-- public."Orders" определение
CREATE TABLE public."Orders" (
	"Id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Weight" float8 NOT NULL,
	"DistrictId" int8 NOT NULL,
	"DeliveryTime" timestamp NOT NULL,
	CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Orders_DistrictId" ON public."Orders" USING btree ("DistrictId");
ALTER TABLE public."Orders" ADD CONSTRAINT "FK_Orders_Districts_DistrictId" FOREIGN KEY ("DistrictId") REFERENCES public."Districts"("Id") ON DELETE CASCADE;


-- public."Deliveries" определение
CREATE TABLE public."Deliveries" (
	"Id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"OrderId" int8 NOT NULL,
	"DistrictId" int8 NOT NULL,
	"LastDeliveryFilterTime" timestamp NOT NULL,
	CONSTRAINT "PK_Deliveries" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Deliveries_DistrictId" ON public."Deliveries" USING btree ("DistrictId");
CREATE INDEX "IX_Deliveries_OrderId" ON public."Deliveries" USING btree ("OrderId");
ALTER TABLE public."Deliveries" ADD CONSTRAINT "FK_Deliveries_Districts_DistrictId" FOREIGN KEY ("DistrictId") REFERENCES public."Districts"("Id") ON DELETE CASCADE;
ALTER TABLE public."Deliveries" ADD CONSTRAINT "FK_Deliveries_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;